/**
 * PACT PROVIDER VERIFICATION — Inventory Service (Product Service)
 * ─────────────────────────────────────────────────────────────────────────────
 * SCRUM 299: POS-S4-013-T2 — Set up Pact provider verification
 *
 * This test verifies that the Inventory/Product Service (provider) satisfies
 * the contracts defined by the POS Frontend (consumer).
 *
 * It loads pact files from the consumer tests and replays interactions
 * against the real running service to verify compatibility.
 *
 * Run with: npm run test:pact:provider
 *
 * Prerequisites:
 *   1. Consumer pact files must exist in ../../tests/pact/pacts/
 *      (run `npm run test:pact:consumer` from root first)
 *   2. Required env vars: NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY
 *
 * For CI:
 *   - Can also verify against pacts published to Pact Broker
 *   - Set PACT_BROKER_BASE_URL env var to enable broker verification
 */

const { Verifier } = require('@pact-foundation/pact');
const path = require('path');

// ── Configuration ─────────────────────────────────────────────────────────────

// The inventory service URL (must be running)
const PROVIDER_BASE_URL = process.env.PROVIDER_BASE_URL || 'http://localhost:4002';

// Path to the pact files generated by consumer tests
const PACT_FILES_DIR = path.resolve(__dirname, '..', '..', '..', '..', 'tests', 'pact', 'pacts');

// Pact Broker URL (optional — for CI integration)
const PACT_BROKER_BASE_URL = process.env.PACT_BROKER_BASE_URL || '';

// ── Provider Verification ─────────────────────────────────────────────────────

describe('🔍 Pact Provider Verification — Inventory Service', () => {

  // Increase timeout for provider verification (involves HTTP calls)
  jest.setTimeout(60000);

  it('should satisfy all consumer contracts', async () => {
    const verifierOptions = {
      provider: 'InventoryService',
      providerBaseUrl: PROVIDER_BASE_URL,

      // State handlers: set up test data depending on the provider state
      // described in consumer tests. These run before each interaction.
      stateHandlers: {
        'products exist in the inventory': async () => {
          // The service queries Supabase for products.
          // In CI, ensure the test DB has seeded product data.
          console.log('[Provider State] Products exist in inventory — using existing DB data');
        },

        'a product with stock exists': async (params) => {
          // The service queries Supabase for a specific product.
          console.log('[Provider State] Product with stock exists:', params);
        },

        'the inventory service is available': async () => {
          // No setup needed — health check endpoint
          console.log('[Provider State] Service is available — no setup needed');
        },
      },

      // Log level for debugging
      logLevel: 'warn',
    };

    // Use Pact Broker if URL is provided (CI mode), otherwise use local files
    if (PACT_BROKER_BASE_URL) {
      verifierOptions.pactBrokerUrl = PACT_BROKER_BASE_URL;
      verifierOptions.consumerVersionSelectors = [
        { mainBranch: true },     // Verify against main branch pacts
        { deployedOrReleased: true }, // Verify against deployed pacts
      ];
      verifierOptions.providerVersion = process.env.GIT_COMMIT || '0.0.0-local';
      verifierOptions.providerVersionBranch = process.env.GIT_BRANCH || 'local';
      verifierOptions.publishVerificationResult = process.env.CI === 'true';

      console.log(`📦 Verifying against Pact Broker: ${PACT_BROKER_BASE_URL}`);
    } else {
      // Local mode: read pact files from the consumer output directory
      verifierOptions.pactUrls = [
        path.resolve(PACT_FILES_DIR, 'POSFrontend-InventoryService.json'),
      ];

      console.log(`📂 Verifying against local pact files: ${PACT_FILES_DIR}`);
    }

    try {
      const output = await new Verifier(verifierOptions).verifyProvider();
      console.log('✅ Pact provider verification passed!');
      console.log(output);
    } catch (error) {
      console.error('❌ Pact provider verification FAILED!');
      console.error(error.message || error);
      throw error;
    }
  });
});
