/**
 * PACT PUBLISH SCRIPT
 * ─────────────────────────────────────────────────────────────────────────────
 * SCRUM 300: POS-S4-013-T3 — Configure Pact Broker and CI integration
 *
 * Publishes consumer pact files to the Pact Broker so that provider
 * verification can be run against them.
 *
 * Usage:
 *   npm run test:pact:publish
 *
 * Environment Variables (from .env or CI):
 *   PACT_BROKER_BASE_URL  — URL of the Pact Broker (default: http://localhost:9292)
 *   PACT_BROKER_USERNAME  — Broker username (default: pact_user)
 *   PACT_BROKER_PASSWORD  — Broker password (default: pact_pass)
 *   GIT_COMMIT            — Git commit SHA for versioning
 *   GIT_BRANCH            — Git branch name
 *
 * OWASP: Broker credentials are loaded from environment variables only,
 * never hardcoded. See .env for local defaults.
 */

const path = require('path');
const { execSync } = require('child_process');
const fs = require('fs');

// ── Configuration (from environment variables) ───────────────────────────────
const PACT_BROKER_BASE_URL = process.env.PACT_BROKER_BASE_URL || 'http://localhost:9292';
const PACT_BROKER_USERNAME = process.env.PACT_BROKER_USERNAME || 'pact_user';
const PACT_BROKER_PASSWORD = process.env.PACT_BROKER_PASSWORD || 'pact_pass';

// Pact files directory (generated by consumer tests)
const PACT_FILES_DIR = path.resolve(__dirname, '..', 'tests', 'pact', 'pacts');

// Version: use git commit hash or fallback
let consumerVersion;
try {
  consumerVersion = process.env.GIT_COMMIT ||
    execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
} catch {
  consumerVersion = `local-${Date.now()}`;
}

// Branch: use git branch or fallback
let branch;
try {
  branch = process.env.GIT_BRANCH ||
    execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim();
} catch {
  branch = 'local';
}

// ── Publish ───────────────────────────────────────────────────────────────────

async function publishPacts() {
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  📦 Pact Contract Publisher');
  console.log('═══════════════════════════════════════════════════════════════');
  console.log(`  Broker URL:        ${PACT_BROKER_BASE_URL}`);
  console.log(`  Consumer Version:  ${consumerVersion}`);
  console.log(`  Branch:            ${branch}`);
  console.log(`  Pact Files Dir:    ${PACT_FILES_DIR}`);
  console.log('═══════════════════════════════════════════════════════════════\n');

  // Check pact files exist
  if (!fs.existsSync(PACT_FILES_DIR)) {
    console.error(`❌ Pact files directory not found: ${PACT_FILES_DIR}`);
    console.error('   Run consumer tests first: npm run test:pact:consumer');
    process.exit(1);
  }

  const pactFiles = fs.readdirSync(PACT_FILES_DIR).filter(f => f.endsWith('.json'));
  if (pactFiles.length === 0) {
    console.error('❌ No pact files found in:', PACT_FILES_DIR);
    console.error('   Run consumer tests first: npm run test:pact:consumer');
    process.exit(1);
  }

  console.log(`Found ${pactFiles.length} pact file(s):`);
  pactFiles.forEach(f => console.log(`  ✓ ${f}`));
  console.log();

  // Publish each pact file to the broker
  for (const pactFile of pactFiles) {
    const pactPath = path.join(PACT_FILES_DIR, pactFile);
    const pactContent = JSON.parse(fs.readFileSync(pactPath, 'utf8'));

    const consumer = pactContent.consumer?.name || 'unknown';
    const provider = pactContent.provider?.name || 'unknown';

    console.log(`📤 Publishing: ${consumer} → ${provider}...`);

    const url = `${PACT_BROKER_BASE_URL}/pacts/provider/${encodeURIComponent(provider)}/consumer/${encodeURIComponent(consumer)}/version/${encodeURIComponent(consumerVersion)}`;

    try {
      const response = await fetch(url, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Basic ' + Buffer.from(`${PACT_BROKER_USERNAME}:${PACT_BROKER_PASSWORD}`).toString('base64'),
        },
        body: fs.readFileSync(pactPath, 'utf8'),
      });

      if (response.ok) {
        console.log(`   ✅ Published successfully (${response.status})`);
      } else {
        const errorText = await response.text();
        console.error(`   ❌ Failed to publish (${response.status}): ${errorText}`);
      }
    } catch (error) {
      console.error(`   ❌ Error publishing pact: ${error.message}`);
      console.error('   Is the Pact Broker running? Try: docker-compose up pact-broker pact-postgres');
    }
  }

  // Tag the version with the branch name
  console.log(`\n🏷️  Tagging consumer version ${consumerVersion} with branch: ${branch}`);
  try {
    const tagUrl = `${PACT_BROKER_BASE_URL}/pacticipants/POSFrontend/versions/${encodeURIComponent(consumerVersion)}/tags/${encodeURIComponent(branch)}`;
    const tagResponse = await fetch(tagUrl, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Basic ' + Buffer.from(`${PACT_BROKER_USERNAME}:${PACT_BROKER_PASSWORD}`).toString('base64'),
      },
    });

    if (tagResponse.ok) {
      console.log(`   ✅ Tagged successfully`);
    } else {
      console.warn(`   ⚠️  Tag failed (${tagResponse.status}) — non-critical`);
    }
  } catch {
    console.warn('   ⚠️  Could not tag version — non-critical');
  }

  console.log('\n✅ Pact publish complete!\n');
}

publishPacts().catch((err) => {
  console.error('Fatal error during pact publishing:', err);
  process.exit(1);
});
